[package]
name = "astroport-dca"
version = "1.0.0"
authors = ["Astroport", "Kaimen Sano"]
edition = "2018"
repository = "https://github.com/astroport-fi/astroport-dca"
homepage = "https://astroport.fi"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cw20 = { version = "0.13.4" }
cosmwasm-std = { version = "1.0.0", features = ["iterator"] }
schemars = "0.8.10"
serde = { version = "1.0.140", default-features = false, features = ["derive"] }
uint = "0.9.3"
regex = "1.6.0"
astroport = { git = "https://github.com/astroport-fi/astroport-core.git", branch = "main", package = "astroport" }

[dev-dependencies]
cosmwasm-schema = "1.0.0"
